FROM python:3.12.7-slim
ENV FLASK_APP=XssApp.py

WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
WORKDIR /code/Victim

# Expose the port the app runs on
EXPOSE 5000

# Define the command to run the application
CMD [ "python3", "-m" , "flask", "run", "--host=172.20.0.2", "--port=5000" ]