FROM python:3.12.7-slim
ENV FLASK_APP=WebAppFirewall/Firewall.py

WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY Classifier /code/Classifier
COPY WebAppFirewall /code/WebAppFirewall
COPY Request /code/Request
COPY config /code/config
COPY logs /code/logs

# Define the command to run the application
CMD [ "python3", "-m", "flask", "run", "--host=172.20.0.2", "--port=8000" ]
