FROM python:3.12.7-slim
ENV FLASK_APP=WebApp/XssApp.py

WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY WebApp /code/WebApp
COPY config /code/config
COPY logs /code/logs

# Define the command to run the application
CMD [ "python3", "-m", "flask", "run", "--host=172.20.0.10", "--port=8001" ]
