FROM python:3.12.7-slim
ENV FLASK_APP=XssApp.py

WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY Victim /code/Victim
COPY logs /code/logs
WORKDIR /code/Victim

# Define the command to run the application
CMD [ "python3", "-m", "flask", "run", "--host=172.20.0.2", "--port=8000" ]
